# Generated by Django 3.1.4 on 2020-12-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('seconedname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('seconedname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('phone', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
