# Generated by Django 3.1.4 on 2021-01-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201224_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='new',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
