# Generated by Django 3.1.4 on 2021-01-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210109_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_review',
            field=models.IntegerField(default=1),
        ),
    ]
