# Generated by Django 3.1.4 on 2021-01-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210109_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Standard', 'Standard'), ('New', 'New'), ('Best Selling', 'Best Selling')], default='New', max_length=20),
        ),
    ]
