# Generated by Django 3.1.4 on 2021-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210110_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Mobiles', 'Mobiles'), ('TVs', 'TVs'), ('Video games & Consols', 'Video games & Consols'), ('PC', 'PC')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
    ]
