# Generated by Django 3.1.4 on 2021-01-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_faqs'),
        ('products', '0013_auto_20210110_2323'),
    ]

    operations = [
    ]
