# Generated by Django 3.1.4 on 2021-01-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210113_1729'),
        ('products', '0015_auto_20210112_1305'),
    ]

    operations = [
    ]
